version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db_queue
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: auth_service
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  microservices-net:
    driver: bridge