spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: C##QUEUE_ADMIN
    password: password123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8444

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
