spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS}
    url: ${URL}
    username: ${USER}
    password: ${PASS}
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8989

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
